export const BUS_TYPE_LINEAR = 'linear'
export const BUS_TYPE_TREE = 'tree'
export const EXPORT_TYPE_INFLUX = 'influx'
export const EXPORT_TYPE_IMPACT = 'impact'
export const TREE_DATA_KEY = '__data__'